package io.quarkiverse.banner.runtime;

import java.util.Locale;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * The FIGlet fonts bundled with, and tested against, this extension.
 * <p>
 * The constant's {@link #fileName()} is the base name of the bundled {@code .flf} resource. Configuration
 * values are matched to a constant by that file name, case-insensitively (see {@link BannerFontConverter}).
 * This file is generated from the bundled fonts.
 */
public enum BannerFont {

    F_1ROW("1row"),
    F_3_D("3-d"),
    F_3D_DIAGONAL("3d_diagonal"),
    F_3X5("3x5"),
    F_4MAX("4max"),
    F_5LINEOBLIQUE("5lineoblique"),
    B1FF("B1FF"),
    DANC4("DANC4"),
    ICL_1900("ICL-1900"),
    ACROBATIC("acrobatic"),
    ALLIGATOR("alligator"),
    ALLIGATOR2("alligator2"),
    ALPHA("alpha"),
    ALPHABET("alphabet"),
    AMC3LINE("amc3line"),
    AMC3LIV1("amc3liv1"),
    AMCAAA01("amcaaa01"),
    AMCNEKO("amcneko"),
    AMCRAZO2("amcrazo2"),
    AMCRAZOR("amcrazor"),
    AMCSLASH("amcslash"),
    AMCSLDER("amcslder"),
    AMCTHIN("amcthin"),
    AMCTUBES("amctubes"),
    AMCUN1("amcun1"),
    ARROWS("arrows"),
    ASCII_NEW_ROMAN("ascii_new_roman"),
    AVATAR("avatar"),
    BANNER3("banner3"),
    BANNER3_D("banner3-D"),
    BANNER4("banner4"),
    BARBWIRE("barbwire"),
    BASIC("basic"),
    BEAR("bear"),
    BELL("bell"),
    BENJAMIN("benjamin"),
    BIG("big"),
    BIGCHIEF("bigchief"),
    BIGFIG("bigfig"),
    BINARY("binary"),
    BLOCK("block"),
    BLOCKS("blocks"),
    BOLGER("bolger"),
    BRACED("braced"),
    BRIGHT("bright"),
    BROADWAY("broadway"),
    BUBBLE("bubble"),
    BULBHEAD("bulbhead"),
    CALGPHY2("calgphy2"),
    CALIGRAPHY("caligraphy"),
    CARDS("cards"),
    CATWALK("catwalk"),
    CHISELED("chiseled"),
    CHUNKY("chunky"),
    COINSTAK("coinstak"),
    COLA("cola"),
    COLOSSAL("colossal"),
    COMPUTER("computer"),
    CONTESSA("contessa"),
    CONTRAST("contrast"),
    COSMIC("cosmic"),
    COSMIKE("cosmike"),
    CRAWFORD("crawford"),
    CRAZY("crazy"),
    CRICKET("cricket"),
    CYBERLARGE("cyberlarge"),
    CYBERMEDIUM("cybermedium"),
    CYBERSMALL("cybersmall"),
    CYGNET("cygnet"),
    DANCINGFONT("dancingfont"),
    DECIMAL("decimal"),
    DEFLEPPARD("defleppard"),
    DIAMOND("diamond"),
    DIETCOLA("dietcola"),
    DIGITAL("digital"),
    DOH("doh"),
    DOOM("doom"),
    DOSREBEL("dosrebel"),
    DOTMATRIX("dotmatrix"),
    DOUBLE("double"),
    DOUBLESHORTS("doubleshorts"),
    DRPEPPER("drpepper"),
    DWHISTLED("dwhistled"),
    EFTICHESS("eftichess"),
    EFTIFONT("eftifont"),
    EFTIPITI("eftipiti"),
    EFTIROBOT("eftirobot"),
    EFTITALIC("eftitalic"),
    EFTIWALL("eftiwall"),
    EFTIWATER("eftiwater"),
    EPIC("epic"),
    FENDER("fender"),
    FIRE_FONT_K("fire_font-k"),
    FIRE_FONT_S("fire_font-s"),
    FLIPPED("flipped"),
    FLOWERPOWER("flowerpower"),
    FOURTOPS("fourtops"),
    FRAKTUR("fraktur"),
    FUNFACE("funface"),
    FUNFACES("funfaces"),
    FUZZY("fuzzy"),
    GEORGI16("georgi16"),
    GHOST("ghost"),
    GHOULISH("ghoulish"),
    GLENYN("glenyn"),
    GOOFY("goofy"),
    GOTHIC("gothic"),
    GRADIENT("gradient"),
    GRAFFITI("graffiti"),
    HENRY3D("henry3d"),
    HEX("hex"),
    HIEROGLYPHS("hieroglyphs"),
    HOLLYWOOD("hollywood"),
    HORIZONTALLEFT("horizontalleft"),
    HORIZONTALRIGHT("horizontalright"),
    IMPOSSIBLE("impossible"),
    INVITA("invita"),
    ISOMETRIC1("isometric1"),
    ISOMETRIC2("isometric2"),
    ISOMETRIC3("isometric3"),
    ISOMETRIC4("isometric4"),
    ITALIC("italic"),
    JAZMINE("jazmine"),
    JERUSALEM("jerusalem"),
    KATAKANA("katakana"),
    KBAN("kban"),
    KEYBOARD("keyboard"),
    KNOB("knob"),
    KONTO("konto"),
    KONTOSLANT("kontoslant"),
    LARRY3D("larry3d"),
    LCD("lcd"),
    LEAN("lean"),
    LETTERS("letters"),
    LILDEVIL("lildevil"),
    LINEBLOCKS("lineblocks"),
    LINUX("linux"),
    LOCKERGNOME("lockergnome"),
    MADRID("madrid"),
    MARQUEE("marquee"),
    MERLIN1("merlin1"),
    MERLIN2("merlin2"),
    MIKE("mike"),
    MINI("mini"),
    MIRROR("mirror"),
    MORSE("morse"),
    MORSE2("morse2"),
    MOSCOW("moscow"),
    MSHEBREW210("mshebrew210"),
    MUZZLE("muzzle"),
    NANCYJ("nancyj"),
    NANCYJ_FANCY("nancyj-fancy"),
    NANCYJ_IMPROVED("nancyj-improved"),
    NANCYJ_UNDERLINED("nancyj-underlined"),
    NIPPLES("nipples"),
    NSCRIPT("nscript"),
    NTGREEK("ntgreek"),
    NVSCRIPT("nvscript"),
    O8("o8"),
    OCTAL("octal"),
    OGRE("ogre"),
    OLDBANNER("oldbanner"),
    OS2("os2"),
    PAWP("pawp"),
    PEAKS("peaks"),
    PEAKSSLANT("peaksslant"),
    PEBBLES("pebbles"),
    PEPPER("pepper"),
    POISON("poison"),
    PUFFY("puffy"),
    PUZZLE("puzzle"),
    RAMMSTEIN("rammstein"),
    RECTANGLES("rectangles"),
    RED_PHOENIX("red_phoenix"),
    RELIEF("relief"),
    RELIEF2("relief2"),
    REVERSE("reverse"),
    ROMAN("roman"),
    ROT13("rot13"),
    ROTATED("rotated"),
    ROUNDED("rounded"),
    ROWANCAP("rowancap"),
    ROZZO("rozzo"),
    RUNIC("runic"),
    RUNYC("runyc"),
    S_RELIEF("s-relief"),
    SANTACLARA("santaclara"),
    SBLOOD("sblood"),
    SCRIPT("script"),
    SERIFCAP("serifcap"),
    SHADOW("shadow"),
    SHIMROD("shimrod"),
    SHORT("short"),
    SLANT("slant"),
    SLIDE("slide"),
    SLSCRIPT("slscript"),
    SMALL("small"),
    SMALLCAPS("smallcaps"),
    SMISOME1("smisome1"),
    SMKEYBOARD("smkeyboard"),
    SMPOISON("smpoison"),
    SMSCRIPT("smscript"),
    SMSHADOW("smshadow"),
    SMSLANT("smslant"),
    SMTENGWAR("smtengwar"),
    SOFT("soft"),
    SPEED("speed"),
    SPLIFF("spliff"),
    STACEY("stacey"),
    STAMPATE("stampate"),
    STAMPATELLO("stampatello"),
    STANDARD("standard"),
    STARSTRIPS("starstrips"),
    STARWARS("starwars"),
    STELLAR("stellar"),
    STOP("stop"),
    STRAIGHT("straight"),
    SUB_ZERO("sub-zero"),
    SWAMPLAND("swampland"),
    SWAN("swan"),
    TANJA("tanja"),
    TENGWAR("tengwar"),
    TERM("term"),
    TEST1("test1"),
    THICK("thick"),
    THIN("thin"),
    THREEPOINT("threepoint"),
    TICKS("ticks"),
    TICKSSLANT("ticksslant"),
    TILES("tiles"),
    TINKER_TOY("tinker-toy"),
    TOMBSTONE("tombstone"),
    TRAIN("train"),
    TREK("trek"),
    TSALAGI("tsalagi"),
    TUBULAR("tubular"),
    TWISTED("twisted"),
    TWOPOINT("twopoint"),
    UNIVERS("univers"),
    USAFLAG("usaflag"),
    VARSITY("varsity"),
    WAVY("wavy"),
    WEIRD("weird"),
    WETLETTER("wetletter"),
    WHIMSY("whimsy"),
    WOW("wow"),
    ;

    private final String fileName;

    BannerFont(String fileName) {
        this.fileName = fileName;
    }

    /** The base name of the bundled {@code .flf} font resource (without extension). */
    public String fileName() {
        return fileName;
    }

    private static final Map<String, BannerFont> BY_NAME = Stream.of(values())
            .collect(Collectors.toUnmodifiableMap(font -> font.fileName.toLowerCase(Locale.ROOT), font -> font));

    /**
     * Returns the font whose {@link #fileName()} matches {@code name} case-insensitively, or {@code null}.
     */
    public static BannerFont fromName(String name) {
        return name == null ? null : BY_NAME.get(name.trim().toLowerCase(Locale.ROOT));
    }
}
