quarkus.console.color=true
quarkus.banner-generator.text={bright-white}Quarkus {red}Banner
#quarkus.banner-generator.font=doom
#quarkus.banner-generator.color=bright-white
#quarkus.banner-generator.background-color=default
quarkus.banner-generator.power-by=true
