quarkus.console.color=true
quarkus.banner-generator.text={bright-yellow}Banner {red}IT
quarkus.banner-generator.font=doom
#quarkus.banner-generator.color=bright-yellow
#quarkus.banner-generator.background-color=default
quarkus.banner-generator.power-by=true
